### ISSUE TITLE
PyPi Publication

### ISSUE THREAD

**Issue by giuliabaldini** [beda-software/fhirpath-py#14]
Hi all!

thank you for implementing this in python, it is very cool! Would you consider publishing the package on PyPi? I am currently using this package as a dependency for a package that we built at our institute, but unfortunately PyPi does not allow git dependencies. Is this in any way a possibility?

Thank you in advance.

Cheers,
Giulia

**Comment by ir4y** [comment]
@ruscoder Could you please publish fhirpath-py?

**Comment by ruscoder** [comment]
Hello @giuliabaldini 

Now the library is available on pypy under the name `fhirpathpy`: https://pypi.org/project/fhirpathpy

```
pip install fhirpathpy
```
