### ISSUE TITLE
FHIRPath with extension token fails with function error and throws an exception - request for support of extension

### ISSUE THREAD

**Issue by coline14s** [beda-software/fhirpath-py#21]
Q: Does fhirpathy support “extensions”
I think it does since when I do this search on the test subdirectory, I get a number of test cases with extension examples. When i run my evaluates, i get exceptions inside my try loop for these examples. [](url)

TEST 1:
These FHIRPath:
ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/dsh_op_clm_val_amt').valueMoney.value 
ExplanationOfBenefit.billablePeriod.extension('https://bluebutton.cms.gov/resources/variables/claim_query_cd').valueCoding.code 

Throw an exception for the attached ExplanationOfBenefit FHIR Resource. I know the extension does not exist for the EOB examples, but should the evaluate throw an exception? 

TEST 2:
This FHIRPath fails when run against the patient resource attached (in zip). Same question except this path seems like it should work, the extension is inside the identifier coding. 

Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value 

[jsonFiles.zip](https://github.com/beda-software/fhirpath-py/files/11888668/jsonFiles.zip)

Any help is appreciated! 
Thanks

**Comment by coline14s** [comment]
Believe that the presence of the token "extension" in the FHIRPath generates a exception. This issue was created to confirm that this is the expected behavior please. Thanks

FYI - Here were all my FHIRPaths that created an exception for the resources attached above:
ExplanationOfBenefit.billablePeriod.extension('https://bluebutton.cms.gov/resources/variables/claim_query_cd').valueCoding.code
ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/ime_op_clm_val_amt').valueMoney.value
ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/ime_op_clm_val_amt').valueMoney.value
ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/dsh_op_clm_val_amt').valueMoney.value
ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/clm_mdcr_non_pmt_rsn_cd').valueCoding.code
ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/clm_uncompd_care_pmt_amt').valueMoney.value
ExplanationOfBenefit.facility.extension('https://bluebutton.cms.gov/resources/variables/clm_fac_type_cd').value.code
ExplanationOfBenefit.extension('https://bluebutton.cms.gov/resources/variables/clm_srvc_clsfctn_type_cd').valueCoding.code
Patient.identifier.where(type.coding.extension('https://bluebutton.cms.gov/resources/codesystem/identifier-currency').valueCoding.code = 'current').where(system = 'http://hl7.org/fhir/sid/us-mbi').value

**Comment by ir4y** [comment]
Hi @coline14s 

Thank you for your contribution. Unfortunately `extension` is not implemented yet.
I will have a look at it next week and most likely implement and release a new version.

**Comment by ir4y** [comment]
@coline14s the simple implementation that works for your case is done.
Please feel free to install it from github.

However extension on primitive types is not supported yet, this part is WIP https://github.com/beda-software/fhirpath-py/pull/22
The new version of the library will be released once primitive types will be supported.

**Comment by ir4y** [comment]
@coline14s new version 0.2.1 with extension support has been released.

**Comment by coline14s** [comment]
thanks ir4y - really appreciated - we're using in a demonstration at the CMS FHIR Connectathon, so if extension works for that example, it will make an excellent impression. testing now.

**Comment by coline14s** [comment]
Tested and works like a champ! Really great outcome! Can't thank you enough. 
Here's our track if folks are interested:
https://confluence.hl7.org/display/FHIR/2023+-+07+CMS+BCDA%2C+AB2D+and+DPC+Introduction+and+Workshop+-+Connectathon+2023-07
