### ISSUE TITLE
No timezone information converting DateTime to string

### ISSUE THREAD

**Issue by m0rl** [beda-software/fhirpath-py#37]
A DateTime object adjusted by time quantity and then converted into a string representation does not include timezone information (which is required according to the specification https://www.hl7.org/fhirpath/#tostring-string).

Example

> (now() + 1 month).toString()

Current

> 2024-03-05T10:10:00.123456

Expected

> 2024-03-05T10:10:00.123+00:00

The formatting is performed here (note the format string does not include timezone)

https://github.com/beda-software/fhirpath-py/blob/feab3bc4ee5ad60c63a032b0c504421925c374eb/fhirpathpy/engine/nodes.py#L772

**Comment by ir4y** [comment]
@atuonufure please check why this case is not covered with tests
