### ISSUE TITLE
Choice elements are not handled properly

### ISSUE THREAD

**Issue by jsdebruin1981** [beda-software/fhirpath-py#38]
According to the FHIR specification: 

2.9.1.1 Polymorphism in FHIR 
For [choice elements](https://hl7.org/fhir/R4/formats.html#choice), where elements can be one of multiple types, e.g. Patient.deceased[x]. In actual instances these will be present as either Patient.deceasedBoolean or Patient.deceasedDateTime. In FHIRPath, choice elements are labeled according to the name without the '[x]' suffix, and children can be explicitly treated as a specific type using the as operation:

(Observation.value as Quantity).unit

The implementation does not handle those, the FHIRpath path only recognizes the actual fieldname, e.g. valueQuantity etc....

**Comment by ir4y** [comment]
Hi @jsdebruin1981

This feature is supported.
You need to specify a version of FHIR to emable this feature.
Here is a related unit test https://github.com/beda-software/fhirpath-py/blob/master/tests/cases/fhir-quantity.yaml#L64
